### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by Harry-Hopkinson** [Harry-Hopkinson/BookFlix#1]
Outside help is welcome.

My index.html images are not loading even though the file path is correct...

**Comment by Harry-Hopkinson** [comment]
![image](https://user-images.githubusercontent.com/63599884/143678527-bf075ecf-0031-4434-b082-336d73e537c8.PNG)

**Comment by Password-Classified** [comment]
Also, do you want help creating the Github Pages?

**Comment by Harry-Hopkinson** [comment]
Yes please  I have set it up but I have had to move my index.html to the root which may of messed up the website

**Comment by Password-Classified** [comment]
Add me to the contributors and I'll see.
